### ISSUE TITLE
Carregar dados do WoS

### ISSUE THREAD

**Issue by denise-scielo** [scieloorg/journals-catalog#9]
Localizar planilha de dados

--> Não estou conseguindo abreviar muito os títulos... ainda estão ficando longos... será que vai dar problema?

**Comment by ednilson** [comment]
@denise-scielo a princípio vamos trabalhar com dados da base **JCR (Journal Citation Reports)** 
https://jcr.incites.thomsonreuters.com
Elaborei um filtro por 'Open Access' e country:'Brazil'.
Seria bom depois checar isso com a @solange-scielo

**Comment by ednilson** [comment]
Os dados fontes baixados do JCR contém registros duplicados:

1,REVISTA BRASILEIRA DE PSIQUIATRIA,REV BRAS PSIQUIATR,1516-4446,"1,319",2.181,2.094,2.190,0.152,46,5.8,8.1,0.002660,0.575,86.960,,57.018,0.30342
1,REVISTA BRASILEIRA DE PSIQUIATRIA,REV BRAS PSIQUIATR,1516-4446,"1,319",2.181,2.094,2.190,0.152,46,5.8,8.1,0.002660,0.575,86.960,,57.018,0.30342

**Comment by ednilson** [comment]
Resolvido no pr#11
